server:
  affinity: ""
  ha:
    enabled: true
    raft:
      enabled: true

  ui:
    enabled: false

  injector:
    enabled: true

  dataStorage:
    size: 4Gi
    storageClass: gp2
    accessMode: ReadWriteOnce

  auditStorage:
    size: 4Gi
    storageClass: gp2
    accessMode: ReadWriteOnce
