apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowler-output-pvc
  namespace: prowler
spec:
  storageClassName: "gp2"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
